name: CI

on: 
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create the documentation issues
      uses: gobeer/godocit@v6
      env:
        PRIVATE_KEY: ${{ secrets.PrivateKey }}

